version: '3.8'

services:
  ui-frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        API_ENDPOINT: http://localhost:8081/bpmn/
        SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
        SUPABASE_PROJECT_ID: ${SUPABASE_PROJECT_ID}

    ports:
      - "8080:80"

  bpmn-backend:
    build:
      context: ./bpmn-server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      CAMUNDA_PASSWORD: ${CAMUNDA_PASSWORD}
      SUPABASE_PROJECT_ID: ${SUPABASE_PROJECT_ID}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      JWT_SECRET: ${JWT_SECRET}
      AWS_ACCESS_KEY_SECRET: ${AWS_ACCESS_KEY_SECRET}