version: '3.8'

services:
  ui:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        API_ENDPOINT: http://localhost:8081/bpmn/
        SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
        SUPABASE_PROJECT_ID: ${SUPABASE_PROJECT_ID}
    image: reqpal/ui:latest
    ports:
      - "8080:80"
    env_file:
      - .env
  bpmn-backend:
    build:
      context: ./bpmn-server
      dockerfile: Dockerfile
    image: reqpal/bpmn-backend:latest
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      SUPABASE_PROJECT_ID: ${SUPABASE_PROJECT_ID}
      SUPABASE_JWT_SECRET: ${SUPABASE_JWT_SECRET}
      SUPABASE_DB_PASSWORD: ${DB_PASSWORD}
      CAMUNDA_PASSWORD: ${CAMUNDA_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_ACCESS_KEY_SECRET: ${AWS_ACCESS_KEY_SECRET}